require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TemporadasController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Temporada. As you add validations to Temporada, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TemporadasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all temporadas as @temporadas" do
      temporada = Temporada.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:temporadas)).to eq([temporada])
    end
  end

  describe "GET show" do
    it "assigns the requested temporada as @temporada" do
      temporada = Temporada.create! valid_attributes
      get :show, {:id => temporada.to_param}, valid_session
      expect(assigns(:temporada)).to eq(temporada)
    end
  end

  describe "GET new" do
    it "assigns a new temporada as @temporada" do
      get :new, {}, valid_session
      expect(assigns(:temporada)).to be_a_new(Temporada)
    end
  end

  describe "GET edit" do
    it "assigns the requested temporada as @temporada" do
      temporada = Temporada.create! valid_attributes
      get :edit, {:id => temporada.to_param}, valid_session
      expect(assigns(:temporada)).to eq(temporada)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Temporada" do
        expect {
          post :create, {:temporada => valid_attributes}, valid_session
        }.to change(Temporada, :count).by(1)
      end

      it "assigns a newly created temporada as @temporada" do
        post :create, {:temporada => valid_attributes}, valid_session
        expect(assigns(:temporada)).to be_a(Temporada)
        expect(assigns(:temporada)).to be_persisted
      end

      it "redirects to the created temporada" do
        post :create, {:temporada => valid_attributes}, valid_session
        expect(response).to redirect_to(Temporada.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved temporada as @temporada" do
        post :create, {:temporada => invalid_attributes}, valid_session
        expect(assigns(:temporada)).to be_a_new(Temporada)
      end

      it "re-renders the 'new' template" do
        post :create, {:temporada => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested temporada" do
        temporada = Temporada.create! valid_attributes
        put :update, {:id => temporada.to_param, :temporada => new_attributes}, valid_session
        temporada.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested temporada as @temporada" do
        temporada = Temporada.create! valid_attributes
        put :update, {:id => temporada.to_param, :temporada => valid_attributes}, valid_session
        expect(assigns(:temporada)).to eq(temporada)
      end

      it "redirects to the temporada" do
        temporada = Temporada.create! valid_attributes
        put :update, {:id => temporada.to_param, :temporada => valid_attributes}, valid_session
        expect(response).to redirect_to(temporada)
      end
    end

    describe "with invalid params" do
      it "assigns the temporada as @temporada" do
        temporada = Temporada.create! valid_attributes
        put :update, {:id => temporada.to_param, :temporada => invalid_attributes}, valid_session
        expect(assigns(:temporada)).to eq(temporada)
      end

      it "re-renders the 'edit' template" do
        temporada = Temporada.create! valid_attributes
        put :update, {:id => temporada.to_param, :temporada => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested temporada" do
      temporada = Temporada.create! valid_attributes
      expect {
        delete :destroy, {:id => temporada.to_param}, valid_session
      }.to change(Temporada, :count).by(-1)
    end

    it "redirects to the temporadas list" do
      temporada = Temporada.create! valid_attributes
      delete :destroy, {:id => temporada.to_param}, valid_session
      expect(response).to redirect_to(temporadas_url)
    end
  end

end
